# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users: IDE settings override these.
# Docs: https://docs.gradle.org/current/userguide/build_environment.html

# JVM args for the daemon (??? 2 ?? ? ?????? ???????).
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable this only ??? *decoupled* multi-project builds.
# More: https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true

# AndroidX namespace is mandatory since AGP 8.
android.useAndroidX=true

# Kotlin code style: "official" / "obsolete"
kotlin.code.style=official

# Make each library?s R class non-transitive (???????? incremental build).
android.nonTransitiveRClass=true

# ?? ???????????: ????????? ??????? ???????? ?????? Kotlin API.
# ???????, ???? ?? ?????? ?????????? ? ?????? ??????? Kotlin.
# ???????, ???? ??????, ????? ?????? ????? ?????? ??? ?????????.
android.disableKotlinStrictApiMode=true
